# Generated by Django 5.2.17 on 2026-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=180, unique=True)),
                ('event_type', models.CharField(choices=[('rtis_position', 'RTIS position'), ('coa_arrival', 'COA arrival'), ('coa_departure', 'COA departure'), ('caution_order', 'Caution order'), ('weather_observation', 'Weather observation')], max_length=40)),
                ('train_number', models.CharField(blank=True, max_length=20)),
                ('station_code', models.CharField(blank=True, max_length=20)),
                ('section_code', models.CharField(blank=True, max_length=40)),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=40)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('accepted', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['train_number', 'event_time'], name='raileta_api_train_n_2181f8_idx'), models.Index(fields=['event_type', 'event_time'], name='raileta_api_event_t_9cd282_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20)),
                ('station_code', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=120)),
                ('scheduled_arrival', models.DateTimeField()),
                ('predicted_arrival', models.DateTimeField()),
                ('confidence_lower', models.DateTimeField()),
                ('confidence_upper', models.DateTimeField()),
                ('delay_minutes', models.FloatField(default=0)),
                ('source_freshness', models.DateTimeField()),
                ('fallback_source', models.CharField(default='WTT', max_length=40)),
                ('model_version', models.CharField(default='event-v1', max_length=80)),
                ('calibration_level', models.FloatField(default=0.8)),
                ('reason_codes', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['train_number', 'generated_at'], name='raileta_api_train_n_d30080_idx')],
                'constraints': [models.UniqueConstraint(fields=('train_number', 'station_code'), name='unique_train_station_forecast')],
            },
        ),
    ]
