# Generated by Django 5.2.17 on 2026-09-05 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainevent',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
