# Generated by Django 5.2.17 on 2026-09-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0003_feedsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsnapshot',
            name='content_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedsnapshot',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='feedsnapshot',
            name='raw_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
