# Generated by Django 5.2.17 on 2026-09-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0005_historical_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrunprediction',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raileta_api.trainevent'),
        ),
    ]
