# Generated by Django 5.2.17 on 2026-09-09 07:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0006_alter_historicalrunprediction_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailSection',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('from_station', models.CharField(max_length=20)),
                ('to_station', models.CharField(max_length=20)),
                ('distance_km', models.FloatField()),
                ('tracks', models.PositiveSmallIntegerField(null=True)),
                ('speed_kmph', models.FloatField(null=True)),
                ('geometry', models.JSONField(default=list)),
                ('source', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('simulation', 'Simulation')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_number', models.CharField(max_length=20)),
                ('train_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('mode', models.CharField(choices=[('live', 'Live'), ('simulation', 'Simulation')], max_length=12)),
                ('priority', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-start_date', 'train_number'],
                'constraints': [models.UniqueConstraint(fields=('train_number', 'start_date', 'mode'), name='dated_train_mode_unique')],
            },
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('station_code', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=120)),
                ('scheduled_arrival', models.DateTimeField(null=True)),
                ('scheduled_departure', models.DateTimeField(null=True)),
                ('distance_km', models.FloatField()),
                ('recovery_minutes', models.FloatField(default=0)),
                ('is_junction', models.BooleanField(default=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='raileta_api.journey')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='raileta_api.railsection')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], max_length=12)),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=120)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('accepted', models.BooleanField(default=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='raileta_api.journey')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raileta_api.journeystop')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_key', models.CharField(max_length=180)),
                ('predicted_arrival', models.DateTimeField()),
                ('lower', models.DateTimeField(null=True)),
                ('upper', models.DateTimeField(null=True)),
                ('baseline_arrival', models.DateTimeField()),
                ('model_version', models.CharField(max_length=80)),
                ('calibration_status', models.CharField(max_length=80)),
                ('features', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='raileta_api.journey')),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raileta_api.journeyevent')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raileta_api.journeystop')),
            ],
            options={
                'ordering': ['issued_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelRelease',
            fields=[
                ('version', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=12)),
                ('artifact_dir', models.CharField(max_length=250)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('mode',), name='one_active_model_per_mode')],
            },
        ),
        migrations.CreateModel(
            name='SectionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('restriction', 'Speed restriction'), ('block', 'Block'), ('congestion', 'Congestion')], max_length=20)),
                ('severity', models.FloatField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('speed_limit_kmph', models.FloatField(null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raileta_api.railsection')),
            ],
        ),
        migrations.AddIndex(
            model_name='journeyevent',
            index=models.Index(fields=['journey', 'event_time'], name='raileta_api_journey_d60d28_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastissue',
            index=models.Index(fields=['journey', 'stop', 'issued_at'], name='raileta_api_journey_e96283_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastissue',
            constraint=models.UniqueConstraint(fields=('journey', 'stop', 'trigger_key', 'model_version'), name='forecast_issuance_unique'),
        ),
        migrations.AddConstraint(
            model_name='journeystop',
            constraint=models.UniqueConstraint(fields=('journey', 'sequence'), name='journey_stop_order_unique'),
        ),
    ]
