# Generated by Django 5.2.17 on 2026-09-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0007_dated_journeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystop',
            name='scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='scheduled_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeystop',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raileta_api.railsection'),
        ),
    ]
