# Generated by Django 5.2.17 on 2026-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raileta_api', '0008_optional_origin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railsection',
            name='geometry',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='railsection',
            name='speed_kmph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='railsection',
            name='tracks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
