import React from 'react';
import { Gauge, Sparkles, X } from 'lucide-react';

const dateTime = (value) => value && Number.isFinite(Date.parse(value))
  ? new Date(value).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'medium', timeStyle: 'short' })
  : '—';
const decimal = (value) => Number.isFinite(value) ? value.toFixed(1) : '—';

export default function HistoricalReplayPanel({ train, onClose }) {
  const replay = train.historical_replay || {};
  const forecast = train.upcoming_stations?.[0];
  const metrics = replay.test_metrics || {};
  if (train.dataset_kind === 'aggregate_profiles') return <section className="ops-panel train-focus-panel">
    <div className="focus-header"><div><p className="ops-eyebrow"><Sparkles /> Held-out average-delay profile</p><h2>{train.train_name}</h2><span>{train.train_number} · {replay.station_name} ({replay.station_code})</span></div><button className="ops-icon-button" onClick={onClose} title="Close train view"><X/></button></div>
    <div className="border-b border-white/10 px-6 py-4"><p className="text-sm text-violet-200" role="status">Replaying recorded aggregate profiles · model has not seen these trains</p><p className="mt-2 text-xs leading-relaxed text-slate-400">Supplied etrain export; provenance unverified. These are station averages, not individual journeys, live events or arrival forecasts.</p></div>
    <div className="grid gap-5 p-6 md:grid-cols-3"><div><p className="text-xs text-slate-500">Recorded average delay</p><strong className="mt-2 block text-2xl text-amber-100">{decimal(replay.recorded_average_delay_minutes)} min</strong></div><div><p className="text-xs text-slate-500">Predicted average delay</p><strong className="mt-2 block text-2xl text-violet-100">{decimal(replay.predicted_average_delay_minutes)} min</strong></div><div><p className="text-xs text-slate-500">Profile absolute error</p><strong className="mt-2 block text-2xl text-white">{decimal(replay.absolute_error_minutes)} min</strong></div></div>
    <div className="border-y border-white/10 px-6 py-4 text-xs leading-relaxed text-slate-400"><p>80%-target TRAIN-calibrated interval for the average: {decimal(replay.lower_minutes)}–{decimal(replay.upper_minutes)} min. Not an individual arrival window.</p><p className="mt-2">Page collected: {dateTime(replay.scraped_at)} IST · Replayed: {dateTime(replay.replayed_at)} IST. Collection time is not arrival time.</p><p className="mt-2">No schedules, movement events, GPS or weather are supplied.</p></div>
    <div className="focus-bottom-grid"><div className="factor-list"><h3 className="mb-3 font-semibold">Top SHAP contributions</h3><p className="mb-3 text-xs text-slate-400">Signed effects from a {decimal(replay.shap_base_minutes)} min baseline—not proven causes.</p>{(train.overall_delay_reasons || []).slice(0,3).map((reason,index)=><div className="factor-row" key={index}><span>◌</span><div><strong>{reason.description}</strong><small>{reason.category}</small></div><time>{reason.minutes>0?'+':''}{decimal(reason.minutes)}m</time></div>)}</div><div className="what-if-card"><div><p className="ops-eyebrow"><Gauge/> Frozen TEST results</p><h3>MAE {decimal(metrics.mae_minutes)} min</h3><span>Coverage {decimal(metrics.coverage_percent)}% · {metrics.n_test} profiles / {metrics.test_trains} unseen trains. Target: 80%.</span><span className="mt-3 block">TRAIN-median baseline MAE: {decimal(metrics.train_median_baseline_mae_minutes)} min.</span><span className="mt-3 block">Model {train.model_version}</span></div></div></div>
  </section>;
  return <section className="ops-panel train-focus-panel">
    <div className="focus-header"><div><p className="ops-eyebrow"><Sparkles /> Historical train focus</p><h2>{train.train_name}</h2><span>Train {train.train_number} · {replay.source_name} → {replay.destination_name}</span></div><button className="ops-icon-button" onClick={onClose} title="Close train view"><X /></button></div>
    <div className="border-b border-white/10 px-6 py-4"><p className="text-sm text-violet-200" role="status">Historical dataset replay · held-out trains · provenance unverified</p><p className="mt-2 text-xs leading-relaxed text-slate-400">The model has not seen these trains or runs during fitting or calibration. This retrospective prediction uses pre-arrival fields, not actual arrival or delay. Source authenticity has not been independently verified.</p></div>
    <div className="grid gap-5 p-6 md:grid-cols-3">
      <div><p className="text-xs text-slate-500">Recorded actual arrival · IST</p><strong className="mt-2 block text-base text-amber-100">{dateTime(replay.original_actual_arrival)}</strong><span className="mt-1 block text-sm text-slate-400">{decimal(replay.actual_delay_minutes)} min recorded delay</span></div>
      <div><p className="text-xs text-slate-500">Model-predicted arrival · IST</p><strong className="mt-2 block text-base text-violet-100">{dateTime(forecast?.predicted_arrival)}</strong><span className="mt-1 block text-sm text-slate-400">{decimal(replay.predicted_delay_minutes)} min predicted delay</span></div>
      <div><p className="text-xs text-slate-500">Absolute error for this run</p><strong className="mt-2 block text-2xl text-violet-100">{decimal(replay.absolute_error_minutes)} min</strong><span className="mt-1 block text-xs text-slate-400">Record {replay.record_id}</span></div>
    </div>
    <div className="border-y border-white/10 px-6 py-4 text-xs leading-relaxed text-slate-400"><p>Original schedule: {dateTime(replay.original_scheduled_arrival)} · Replayed at: {dateTime(replay.replayed_at)} · IST</p><p className="mt-2">TRAIN-calibrated arrival window: {dateTime(forecast?.confidence_lower)} – {dateTime(forecast?.confidence_upper)}</p><p className="mt-2">No intermediate station positions, GPS, departure events, or route-progress estimates are available in this dataset.</p></div>
    <div className="focus-bottom-grid"><div className="factor-list"><div className="route-caption"><div><p className="ops-eyebrow"><Sparkles /> Prediction explanations</p><h3>Top SHAP contributions</h3></div></div><p className="mb-3 text-xs text-slate-400">Signed effects relative to the model baseline—not proven causes.</p>{(train.overall_delay_reasons || []).slice(0, 3).map((reason, index) => <div className="factor-row" key={index}><span>{reason.icon || '◌'}</span><div><strong>{reason.description}</strong><small>{reason.category}</small></div><time>{reason.minutes > 0 ? '+' : ''}{decimal(reason.minutes)}m</time></div>)}</div><div className="what-if-card"><div><p className="ops-eyebrow"><Gauge /> Separate TEST evaluation</p><h3>MAE {decimal(metrics.mae_minutes)} min</h3><span>Empirical window coverage {decimal(metrics.coverage_percent)}% across {metrics.n_test ?? '—'} runs. Target: 80%; not a guarantee for an individual run.</span><span className="mt-3 block">Model {train.model_version}</span></div></div></div>
  </section>;
}
